# Generated by Django 4.1.6 on 2023-04-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(max_length=300)),
                ('op1', models.CharField(max_length=300)),
                ('op2', models.CharField(max_length=300)),
                ('op3', models.CharField(max_length=300)),
            ],
        ),
    ]
