# Generated by Django 4.1.6 on 2023-04-30 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionmodel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='questionmodel',
            name='op1',
        ),
        migrations.RemoveField(
            model_name='questionmodel',
            name='op2',
        ),
        migrations.RemoveField(
            model_name='questionmodel',
            name='op3',
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='ques',
            field=models.CharField(max_length=300, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(max_length=300)),
                ('vote', models.IntegerField(default=0)),
                ('ques', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='auapp.questionmodel')),
            ],
        ),
    ]
