# Generated by Django 4.1.6 on 2023-04-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auapp', '0002_remove_questionmodel_id_remove_questionmodel_op1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(max_length=300)),
                ('op1', models.CharField(max_length=300)),
                ('op2', models.CharField(max_length=300)),
                ('op3', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='QuestionModel',
        ),
    ]
