# Generated by Django 4.1.6 on 2023-05-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auapp', '0003_question_delete_choice_delete_questionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
