# Generated by Django 4.1.6 on 2023-05-01 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auapp', '0004_question_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='vote',
        ),
    ]
