# Generated by Django 4.1.6 on 2023-05-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auapp', '0005_remove_question_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option_one_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='option_three_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='option_two_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='ques',
            field=models.TextField(),
        ),
    ]
