# Generated by Django 4.1.6 on 2023-05-06 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auapp', '0006_question_option_one_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='op1',
            field=models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(2, 'the field must contain at least 2 characters')]),
        ),
        migrations.AlterField(
            model_name='question',
            name='op2',
            field=models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(2, 'the field must contain at least 2 characters')]),
        ),
        migrations.AlterField(
            model_name='question',
            name='op3',
            field=models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(2, 'the field must contain at least 2 characters')]),
        ),
        migrations.AlterField(
            model_name='question',
            name='ques',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(2, 'the field must contain at least 2 characters')]),
        ),
    ]
